version: '3'
services:
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: database
            MYSQL_USER: admin
            MYSQL_PASSWORD: password

    web:
        build: .
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8010:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: rootpassword 

volumes:
        db_data: {}